config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, module: :devise, path: 'backend/auth'

  root to: 'frontend/site#index'
  namespace :frontend, path: '' do
    get 'about' => 'site#about'
    get 'contact' => 'site#contact'

    resources :projects,  only: [:index, :show]
    resources :applications, only: [:create]
    resources :vacancies, only: [:index]

    resources :news_articles, path: 'news', only: [:index, :show]
  end

  get 'admin' => redirect('backend')
  namespace :backend do
    get '/' => redirect('backend/news')

    resources :projects
    #resources :vacancies
    resources :applications, only: [:index, :show, :destroy]
    resources :news_articles, path: 'news', except: [:show]

    resources :galleries, only: [] do
      resources :gallery_photos, only: [:index, :create, :destroy], path: 'photos'
    end

    resources :admin_users, path: 'admin-users'

    resources :wysiwyg_attachments, only: [:index, :create, :show]
    resources :wysiwyg_videos, only: [:index, :create, :show]

    resources :site_settings, path: 'settings', only: [:index] do
      collection do
        put :update
      end
    end
  end
end

app/models/news_article.rb
class NewsArticle < ActiveRecord::Base
  include Concerns::Sluggable

  sluggable :title
  scope :latest,    -> { order('updated_at DESC') }
  scope :published, -> { where(published: true)  }

  mount_uploader :cover, NewsArticleCoverUploader

  validates_presence_of :title, :content, :author
  validates_length_of :author, maximum: 31
  validates_length_of :title, maximum: 255
  validates_length_of :readout, maximum: 1_500
  validates_length_of :content, maximum: 50_000
end

app/controllers/backend/news_articles_controller.rb
class Backend::NewsArticlesController < BackendController
  before_action :find_news_article, only: [:show, :edit, :update, :destroy]

  def index
    @q = NewsArticle.latest.search(params[:q])
    @news_articles = @q.result(distinct: true).paginate(paginate_params)
  end

  def new
    @news_article = NewsArticle.new
  end

  def create
    @news_article = NewsArticle.new(news_article_params)
    if @news_article.save
      redirect_to backend_news_articles_path, notice: 'Article was successfully updated'
    else
      render 'new', alert: 'Check out the errors below'
    end
  end

  def edit
  end

  def update
    if @news_article.update(news_article_params)
      redirect_to backend_news_articles_path, notice: 'Article was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @news_article.destroy
    redirect_to backend_news_articles_path, notice: 'Article was successfully destroyed'
  end

  protected
  def find_news_article
    @news_article = NewsArticle.friendly.find(params[:id])
  end

  def news_article_params
    params.require(:news_article).permit(:title, :readout, :content, :cover, :author, :published)
  end
end

app/controllers/frontend/applications_controller.rb
class Frontend::ApplicationsController < FrontendController
  def create
    #@vacancy = Vacancy.friendly.find(params[:vacancy_id])

    @application = Application.new(application_params)
    #@application.location = @vacancy.location
    if @application.save
      render 'success', layout: false
    else
      render partial: 'frontend/vacancies/form', layout: false
    end
  end

  protected

  def application_params
    params.require(:application).permit(:first_name, :last_name, :phone, :email, :resume, :cover_letter,
                                        :portfolio_url, :linkedin_url, :website)
  end
end

app/controllers/frontend/news_articles_controller.rb
class Frontend::NewsArticlesController < FrontendController
  def index
    @news_articles = NewsArticle.published.latest.limit(9)
  end

  def show
    @news_article = NewsArticle.published.friendly.find(params[:id])
  end
end

app/controllers/frontend/projects_controller.rb
class Frontend::ProjectsController < FrontendController
  def index
    @projects = Project.latest.limit(9).to_a
  end

  def show
    @project = Project.friendly.find(params[:id])
  end
end

app/controllers/frontend/site_controller.rb
class Frontend::SiteController < FrontendController

  def index
    @latest_projects = Project.latest.limit(8).to_a
    @latest_news_articles = NewsArticle.published.latest.limit(2).to_a
    render 'index', layout: 'frontend_homepage'
  end

  def about
  end

  def contact
  end
end

app/controllers/frontend/vacancies_controller.rb
class Frontend::VacanciesController < FrontendController
  def index
    #@vacancies = Vacancy.order('created_at desc')
    @application = Application.new
  end

  def show
    #@vacancy = Vacancy.friendly.find(params[:id])
  end
end

app/controllers/frontend_controller.rb
module Frontend; end
class FrontendController < ActionController::Base
  layout 'frontend'
  before_action :fetch_settings
  helper FrontendHelper


  def full_url(url)
    #[RailsOpro.application.config.asset_host, url].join
  end
  helper_method :full_url

  protected

  def fetch_settings
    @settings = SiteSetting.all.map { |s| [s.code.to_sym, s.value]}.to_h
  end
end

app/helpers/frontend_helper.rb
module FrontendHelper
  def background_image(image_filename)
    "background-image: url(#{ asset_path image_filename })"
  end

  def widget(name, type=:show, *args)
    render_cell name, type, *args
  end
end

app/views/frontend/news_articles/_comments.html.slim
#disqus_thread
javascript:
  var disqus_shortname = 'pixelwebsite'; // required: replace example with your forum shortname

   (function() {
     var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
     dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
     (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
     })();
noscript
  Please enable JavaScript to view the
  a href="https://disqus.com/?ref_noscript"  comments powered by Disqus.

app/views/frontend/news_articles/index.html.slim
- content_for(:title) { 'Journal' }

.news
  .container.top-video-container
    video.bg.hidden-xs autoplay="autoplay" loop="loop" muted="false" poster="#{ asset_path 'journal-cover.jpg' }"
      source type="video/mp4" src="https://s3.amazonaws.com/pixel-website-videos/Comp+1_1.mp4"
    = image_tag 'projects-cover.jpg', class: 'bg visible-xs'
    .overlay

    h1 Our Thoughts.

  .container
    .title-top
      h1 Recent Articles

  .container.move-down-on-scroll(data-move-down)
    .icon-arrow
      = image_tag 'icons/icon-arrow-dark.svg', class: 'dark-arrow'
      = image_tag 'icons/icon-arrow.svg', class: 'light-arrow'

    .news-list.row
      - @news_articles.each do |article|
        .col-md-4.col-sm-6.col-xs-12
          = widget :news_tile, :show, article: article

  /= render 'frontend/action_button'

app/views/frontend/news_articles/show.html.slim
- content_for(:title) { @news_article.title }
- content_for(:description) { @news_article.readout }

.news
  .main-article-container(style="background-image: url('#{@news_article.cover.url(:main) || image_path('frontend/news_articles/journal.jpg')}')")
    .overlay
    .thumbnail
      = link_to frontend_news_article_path(@news_article), class: 'carousel-caption' do
        .specification
          span.section> JOURNAL
          span.delimiter
            ' /
          span.date = l @news_article.created_at, format: :short
        .content-info
          h1.title = @news_article.title
          h2.descr = @news_article.readout

  .container
    article.article
      .author Author: #{@news_article.author}

      /h1.headline = @news_article.readout
      .wysiwyg-content.content == @news_article.content
      .share
        = widget :social_share, :show, url: frontend_news_article_url(@news_article), title: @news_article.title, image: (@news_article.cover.url(:main) if @news_article.cover.present?)

      hr

      .comments
        h3 Comments
        = render 'comments'

  /= render 'action_button'