config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, module: :devise, path: 'backend/auth'

  root to: 'frontend/site#index'
  namespace :frontend, path: '' do
    get 'about' => 'site#about'
    get 'contact' => 'site#contact'

    resources :projects,  only: [:index, :show]
    resources :applications, only: [:create]
    resources :vacancies, only: [:index]

    resources :news_articles, path: 'news', only: [:index, :show]
  end

  get 'admin' => redirect('backend')
  namespace :backend do
    get '/' => redirect('backend/news')

    resources :projects
    #resources :vacancies
    resources :applications, only: [:index, :show, :destroy]
    resources :news_articles, path: 'news', except: [:show]

    resources :galleries, only: [] do
      resources :gallery_photos, only: [:index, :create, :destroy], path: 'photos'
    end

    resources :admin_users, path: 'admin-users'

    resources :wysiwyg_attachments, only: [:index, :create, :show]
    resources :wysiwyg_videos, only: [:index, :create, :show]

    resources :site_settings, path: 'settings', only: [:index] do
      collection do
        put :update
      end
    end
  end
end

app/controllers/frontend/applications_controller.rb
class Frontend::ApplicationsController < FrontendController
  def create
    #@vacancy = Vacancy.friendly.find(params[:vacancy_id])

    @application = Application.new(application_params)
    #@application.location = @vacancy.location
    if @application.save
      render 'success', layout: false
    else
      render partial: 'frontend/vacancies/form', layout: false
    end
  end

  protected

  def application_params
    params.require(:application).permit(:first_name, :last_name, :phone, :email, :resume, :cover_letter,
                                        :portfolio_url, :linkedin_url, :website)
  end
end

app/controllers/frontend/news_articles_controller.rb
class Frontend::NewsArticlesController < FrontendController
  def index
    @news_articles = NewsArticle.published.latest.limit(9)
  end

  def show
    @news_article = NewsArticle.published.friendly.find(params[:id])
  end
end

app/controllers/frontend/projects_controller.rb
class Frontend::ProjectsController < FrontendController
  def index
    @projects = Project.latest.limit(9).to_a
  end

  def show
    @project = Project.friendly.find(params[:id])
  end
end

app/controllers/frontend/site_controller.rb
class Frontend::SiteController < FrontendController

  def index
    @latest_projects = Project.latest.limit(8).to_a
    @latest_news_articles = NewsArticle.published.latest.limit(2).to_a
    render 'index', layout: 'frontend_homepage'
  end

  def about
  end

  def contact
  end
end

app/controllers/frontend/vacancies_controller.rb
class Frontend::VacanciesController < FrontendController
  def index
    #@vacancies = Vacancy.order('created_at desc')
    @application = Application.new
  end

  def show
    #@vacancy = Vacancy.friendly.find(params[:id])
  end
end

app/controllers/frontend_controller.rb
module Frontend; end
class FrontendController < ActionController::Base
  layout 'frontend'
  before_action :fetch_settings
  helper FrontendHelper


  def full_url(url)
    #[RailsOpro.application.config.asset_host, url].join
  end
  helper_method :full_url

  protected

  def fetch_settings
    @settings = SiteSetting.all.map { |s| [s.code.to_sym, s.value]}.to_h
  end
end

app/helpers/frontend_helper.rb
module FrontendHelper
  def background_image(image_filename)
    "background-image: url(#{ asset_path image_filename })"
  end

  def widget(name, type=:show, *args)
    render_cell name, type, *args
  end
end

app/views/frontend/site/about.html.slim
.about.container-fluid
  .container.top-video-container
    video.bg.hidden-xs autoplay="autoplay" loop="loop" muted="false" poster="#{ asset_path 'about-us-cover.jpg' }"
      source type="video/mp4" src="https://s3.amazonaws.com/pixel-website-videos/about-us-top.mp4"
    = image_tag 'about-us-cover.jpg', class: 'bg visible-xs'
    .overlay

    h1 Not Just Ideas.


  .container
    .who-we-are.section-text-block.section-block
      h2 Who We Are.
      p.text Pixel is a lean, creative, award-winning digital agency with an insatiable thirst for beautiful design and a no-nonsense approach to getting things done.
      p.text We are artists and thinkers. Coders and ﬁne-tuners. Writers and directors. Experts in technology and branding connoisseurs. Our energetic team pull problems apart, tease out solutions, build out from the back-end and then wrap our projects up with a bow.

  .container
    .row.container-section-block
      .col-md-6.col-sm-12.col-xs-12
        .content-block
          h2 What We Do.
          p.text
            | We could say that we build beautiful websites, addictive apps, engaging films, inventive content and powerful social media campaigns - all driven by a ruthless commitment to design that blows minds.
          p.text
            | But what we really do is help companies understand the digital world, seek out lost opportunities, capitalize on existing opportunities and invent new products that captivate their customers.

      .col-md-6.col-sm-12.col-xs-12.line
        .content-block
          h2 What We Think.
          p.text We believe that the secret behind captivating an audience and leading them down your path lies in creative storytelling. That means surprising and delighting consumers with rich, beautiful content at every touch point.
          p.text Whether that’s an app they can’t put down, a ﬁlm that moves them, a tablet experience that inspires them or a website that keeps them coming back for more. Stories leave a mark that stand the test of time.

  .container
    .roadmap.content-block.section-block
      .roadmap-container
        h2 Roadmap.
        = image_tag 'roadmap.png'

  .container
    .section-text-block.section-block
      h2 Why Our Model Works.
      p.text Our organizational structure is ﬂat, collaborative and highly effective. Ask any of our clients. We’ve done away with layers of unnecessary account management and enlisted passionate, multi-talented producers to work directly with our clients from brief to delivery.
      p.text Simply put, this means better work, delivered faster, for less money. Just like our namesake, our teams are small but perfectly formed.

  /.container
    .team.section-text-block
      h2 Our Team
      h3.text Work Hard, Play harder

  /.container
    .row.team-members
      .col-sm-4.col-xs-12.member
        = image_tag 'about-member-1.jpg', class: 'section-image'
        .overlay
        .content
          .name Nick
          .descr Lorem ipsum lorem  ipsum lorem  ipsum lorem  ipsum lorem  ipsum lorem  ipsum lorem  ipsum lorem

      .col-sm-4.col-xs-12.member
        = image_tag 'about-member-2.jpg', class: 'section-image'
        .overlay
        .content
          .name George
          .descr Lorem ipsum lorem  ipsum lorem  ipsum lorem  ipsum lorem  ipsum lorem  ipsum lorem  ipsum lorem

      .col-sm-4.col-xs-12.member
        = image_tag 'about-member-3.jpg', class: 'section-image'
        .overlay
        .content
          .name Artem
          .descr Lorem ipsum lorem  ipsum lorem  ipsum lorem  ipsum lorem  ipsum lorem  ipsum lorem  ipsum lorem

  .container
    #services.services.section-text-block
      h2 Services.

      .services-list
        .row
          .col-sm-6.col-xs-12.service.left
            h4.name Business Strategy
            .descr Market Opportunity Analysis, Business and Product Innovation, Organization Planning and Development, Partnership Strategy, Vendor Selection and Management.
          .col-sm-6.col-xs-12.service.right
            h4.name User Experience Design
            .descr Omnichannel Design, Digital In-Store Design, Product Creation, Responsive, App & Mobile Design.
        .row
          .col-sm-6.col-xs-12.service.left
            h4.name Social
            .descr Social Media & PR, Community Management, Influencer Engagement, Media Relations, Measurement & Analytics.
          .col-sm-6.col-xs-12.service.right
            h4.name Brand Planning
            .descr Integrated Marketing Strategy, Brand Strategy, Digital Brand Translation.
        .row
          .col-sm-6.col-xs-12.service.left
            h4.name Creative
            .descr Integrated Campaigns, Copywriting, Editorial Services, Live-Action Production, Motion Graphics & Animation, Art Production, Design Production.
          .col-sm-6.col-xs-12.service.right
            h4.name SEO + Inbound Marketing
            .descr On-Page Strategy, Competitive Inbound Analysis, Search Social Strategy, Local Optimization, Paid Search.

        .row
          .col-sm-6.col-xs-12.service.left
            h4.name Data Science
            .descr Consumer Data Analytics, Strategy & Implementation, Marketing, Social & CRM Analytics, Data Visualization, Data Strategy.
          .col-sm-6.col-xs-12.service.right
            h4.name Technology
            .descr Mobile & Multiplatform Apps, E-Commerce, Digital In-Store, Web Applications, Content Management Systems, Emerging Platforms, Gesture Recognition.

        .row
          .col-sm-6.col-xs-12.service.left
            h4.name Research
            .descr In-Person Observational Research, Online Community Research, Mobile Qualitative Research, Usability Testing, Market Segmentation.
          .col-sm-6.col-xs-12.service.right
            h4.name Content
            .descr Brand Publishing, Information Strategy, Publishing Management, Content Development.
        .row
          .col-sm-6.col-xs-12.service.left
            h4.name CRM
            .descr Loyalty Initiatives, Customer Lifetime Value (CLV) Management, Segment Development and Evaluation, Marketing Automation, Customer Data Management.
          .col-sm-6.col-xs-12.service.right
            h4.name Display
            .descr IAB Banners, Rich Media, Mobile, HTML5


  .container
    .clients.section-text-block
      h2.title Our Clients.

      .list.row
        .col-md-4.col-sm-6.col-xs-12.client.border-right.border-bottom
          .image-container
            = image_tag 'clients/marilyn-monroe.png'
        .col-md-4.col-sm-6.col-xs-12.client.border-right.border-bottom
          .image-container
            = image_tag 'clients/pg.png'
        .col-md-4.col-sm-6.col-xs-12.client.border-bottom
          .image-container
            = image_tag 'clients/john-varvatos-logo.png'

        .col-md-4.col-sm-6.col-xs-12.client.border-right
          .image-container
            = image_tag 'clients/white-wall.png'
        .col-md-4.col-sm-6.col-xs-12.client.border-right
          .image-container
            = image_tag 'clients/bottega-veneta.png'
        .col-md-4.col-sm-6.col-xs-12.client
          .image-container
            = image_tag 'clients/nomad.png'


  /= render 'action_button'

app/views/frontend/site/contact.html.slim
script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAPbKuT7t4LRnkpaFLlR7aja73v-7te15w&sensor=false"
//CONTACT
.contact-us.container

  .main-info
    .title-contact
      h1
        | Call. We’re All Ears.
    .contact-types
      .row
        .col-md-4.item
          a.title href=""
            | New Business
          = link_to 'newbusiness@pixel-nyc.com', 'mailto:newbusiness@pixel-nyc.com', class: 'link'
        .col-md-4.item.line
          a.title href=""
            | Media/Press
          = link_to 'press@pixel-nyc.com', 'mailto:press@pixel-nyc.com', class: 'link'
        .col-md-4.item
          a.title href=""
            | Careers
          = link_to 'jobs@pixel-nyc.com', 'mailto:jobs@pixel-nyc.com', class: 'link'
  .our-offices
    | Our Offices
    .icon-arrow
      = image_tag 'icons/icon-arrow.svg'
  .locations
    .offices
      .row
        .col-md-6.col-sm-12.col-xs-12
          .locations-img
            a.thumbnail href=""
              .overlay-info-contact
                .city-offices
                  p.title NEW YORK
              = image_tag 'site/contact/contact1.jpg'
            .text-offices
              .info-offices
                .address 568 Broadway, 11th Floor NY, NY 10012
                = link_to 'nick@pixel-nyc.com', 'mailto:nick@pixel-nyc.com', class: 'link'
                = link_to '+1-917-969-4461', 'tel:+19179694461', class: 'link'
              a.get-directions target="_blank" href="https://www.google.com/maps/place/568+Broadway,+New+York,+NY+10012,+USA/@40.7242802,-73.9973541,17z/data=!3m1!4b1!4m2!3m1!1s0x89c2598ee26c84db:0xc3e71c7bf935f26c"
                | GET DIRECTIONS.
        .col-md-6.col-sm-12.col-xs-12
          .locations-img
            a.thumbnail href=""
              .overlay-info-contact
                .city-offices
                  p.title LONDON
              .overlay-info-contact
              = image_tag 'site/contact/contact2.jpg'
            .text-offices
              .info-offices
                .address
                  | 68 - 80 Hanbury St London, E1 5JL
                = link_to 'george@pixel-nyc.com', 'mailto:george@pixel-nyc.com', class: 'link'
                = link_to '+44-0750-719-7286', 'tel:4407507197286', class: 'link'
              a.get-directions target="_blank" href="https://www.google.com/maps/place/68-80+Hanbury+St,+London+E1+5JL,+UK/@51.5202136,-0.0711258,16z/data=!4m2!3m1!1s0x48761cb5fd76a2bd:0x54b079b57e738077"
                | GET DIRECTIONS.



/= render 'action_button'

app/views/frontend/site/index.html.slim
- content_for(:body_class) { 'gallery' }

.home
  = widget :projects_carousel

  .main
    .container.main-message
      .quote
        .quote-text The greatest source of creativity is a timeline & a budget
        .quote-author - Frank Gehry

    .container.main-content.home(data-main-content)
      .tails-wrapper
        .row
          .col-md-3.col-sm-6.col-xs-12 = widget :project_tile, :show, project: @latest_projects.shift

          .col-md-3.col-sm-6.col-xs-12 = widget :news_tile, :show, article: @latest_news_articles.shift
          .col-md-3.col-sm-6.col-xs-12 = widget :project_tile, :show, project: @latest_projects.shift
          .col-md-3.col-sm-6.col-xs-12 = widget :project_tile, :show, project: @latest_projects.shift
          .col-md-3.col-sm-6.col-xs-12 = widget :project_tile, :show, project: @latest_projects.shift
          .col-md-3.col-sm-6.col-xs-12 = widget :project_tile, :show, project: @latest_projects.shift
          .col-md-3.col-sm-6.col-xs-12 = widget :news_tile, :show, article: @latest_news_articles.shift
          .col-md-3.col-sm-6.col-xs-12 = widget :project_tile, :show, project: @latest_projects.shift
          .col-md-3.col-sm-6.col-xs-12 = widget :project_tile, :show, project: @latest_projects.shift

        - if @latest_projects.any?
          .row
            - 4.times do |item|
              .col-md-3.col-sm-6.col-xs-12 = widget :project_tile, :show, project: @latest_projects.shift

    .container
      = link_to frontend_projects_path, class: 'view-more-works' do
        | View more Works
        = image_tag 'icons/icon-double-right.svg', class: 'icon icon-right'



    /= render 'frontend/action_button'

  = render 'frontend/footer'