config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, module: :devise, path: 'backend/auth'

  root to: 'frontend/site#index'
  namespace :frontend, path: '' do
    get 'about' => 'site#about'
    get 'contact' => 'site#contact'

    resources :projects,  only: [:index, :show]
    resources :applications, only: [:create]
    resources :vacancies, only: [:index]

    resources :news_articles, path: 'news', only: [:index, :show]
  end

  get 'admin' => redirect('backend')
  namespace :backend do
    get '/' => redirect('backend/news')

    resources :projects
    #resources :vacancies
    resources :applications, only: [:index, :show, :destroy]
    resources :news_articles, path: 'news', except: [:show]

    resources :galleries, only: [] do
      resources :gallery_photos, only: [:index, :create, :destroy], path: 'photos'
    end

    resources :admin_users, path: 'admin-users'

    resources :wysiwyg_attachments, only: [:index, :create, :show]
    resources :wysiwyg_videos, only: [:index, :create, :show]

    resources :site_settings, path: 'settings', only: [:index] do
      collection do
        put :update
      end
    end
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  include Concerns::Sluggable
  include Concerns::Galleryable
  include Concerns::Arrayable

  sluggable :name
  arrayable :services
  enum carousel_text_color: { light: 'light', dark: 'dark' }

  scope :latest,      -> { order('created_at DESC') }
  scope :in_carousel, -> { where(in_carousel: true)  }

  validates_presence_of :name, :tile_cover
  validates_length_of :name, :carousel_title, :link, :maximum => 255
  validates_length_of :description, :carousel_description, maximum: 1000
  validates_length_of :content, maximum: 50_000
  validates :cover, :tile_cover, :carousel_cover, file_size: { maximum: 10.megabytes }
  validates :video, file_size: { maximum: 50.megabytes }

  mount_uploader :tile_cover, ProjectTileCoverUploader
  mount_uploader :carousel_cover, ProjectCarouselCoverUploader
  mount_uploader :cover, ProjectCoverUploader
  mount_uploader :video, VideoUploader
end

app/controllers/backend/projects_controller.rb
class Backend::ProjectsController < BackendController
  before_action :find_item, only: [:show, :edit, :update, :destroy]


  def index
    @q = Project.latest.search(params[:q])
    @projects = @q.result(distinct: true).paginate(paginate_params)
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to backend_projects_path, notice: 'Project was successfully updated'
    else
      render 'new', alert: 'Check out the errors below'
    end
  end

  def edit
  end

  def update
    if @project.update(project_params)
      redirect_to edit_backend_project_path(@project), notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to backend_projects_path, notice: 'Project was successfully destroyed'
  end

  protected
  def find_item
    @project = Project.friendly.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :description, :content, :tile_cover, :carousel_cover, :in_carousel,
                                    :cover, :video, :virtual_services, :carousel_title, :carousel_description, :link,
                                    :carousel_text_color)
  end
end

app/controllers/frontend/applications_controller.rb
class Frontend::ApplicationsController < FrontendController
  def create
    #@vacancy = Vacancy.friendly.find(params[:vacancy_id])

    @application = Application.new(application_params)
    #@application.location = @vacancy.location
    if @application.save
      render 'success', layout: false
    else
      render partial: 'frontend/vacancies/form', layout: false
    end
  end

  protected

  def application_params
    params.require(:application).permit(:first_name, :last_name, :phone, :email, :resume, :cover_letter,
                                        :portfolio_url, :linkedin_url, :website)
  end
end

app/controllers/frontend/news_articles_controller.rb
class Frontend::NewsArticlesController < FrontendController
  def index
    @news_articles = NewsArticle.published.latest.limit(9)
  end

  def show
    @news_article = NewsArticle.published.friendly.find(params[:id])
  end
end

app/controllers/frontend/projects_controller.rb
class Frontend::ProjectsController < FrontendController
  def index
    @projects = Project.latest.limit(9).to_a
  end

  def show
    @project = Project.friendly.find(params[:id])
  end
end

app/controllers/frontend/site_controller.rb
class Frontend::SiteController < FrontendController

  def index
    @latest_projects = Project.latest.limit(8).to_a
    @latest_news_articles = NewsArticle.published.latest.limit(2).to_a
    render 'index', layout: 'frontend_homepage'
  end

  def about
  end

  def contact
  end
end

app/controllers/frontend/vacancies_controller.rb
class Frontend::VacanciesController < FrontendController
  def index
    #@vacancies = Vacancy.order('created_at desc')
    @application = Application.new
  end

  def show
    #@vacancy = Vacancy.friendly.find(params[:id])
  end
end

app/controllers/frontend_controller.rb
module Frontend; end
class FrontendController < ActionController::Base
  layout 'frontend'
  before_action :fetch_settings
  helper FrontendHelper


  def full_url(url)
    #[RailsOpro.application.config.asset_host, url].join
  end
  helper_method :full_url

  protected

  def fetch_settings
    @settings = SiteSetting.all.map { |s| [s.code.to_sym, s.value]}.to_h
  end
end

app/helpers/frontend_helper.rb
module FrontendHelper
  def background_image(image_filename)
    "background-image: url(#{ asset_path image_filename })"
  end

  def widget(name, type=:show, *args)
    render_cell name, type, *args
  end
end

app/views/frontend/projects/_gallery.html.slim
.swiper-gallery
  .swiper-container.project-slider(data-project-slider)
    .swiper-wrapper
      - gallery.gallery_photos.each do |gallery_photo|
        .swiper-slide
          = image_tag gallery_photo.photo.url(:main)

    .swiper-button-next
    .swiper-button-prev

app/views/frontend/projects/index.html.slim
.projects
  .container.top-video-container
    video.bg.hidden-xs autoplay="autoplay" loop="loop" muted="false" poster="#{ asset_path 'projects-cover.jpg' }"
      source type="video/mp4" src="https://s3.amazonaws.com/pixel-website-videos/work-top.mp4"
    = image_tag 'projects-cover.jpg', class: 'bg visible-xs'
    .overlay

    h1 Gettin' It.

  .container
    .title-top
      h1 Recent Work

  .container.move-down-on-scroll(data-move-down)
    .icon-arrow
      = image_tag 'icons/icon-arrow-dark.svg', class: 'dark-arrow'
      = image_tag 'icons/icon-arrow.svg', class: 'light-arrow'

    .cases-list
      .row
        - @projects.each do |project|
          .col-lg-3.col-sm-6.col-xs-12 = widget :project_tile, :show, project: project

/= render 'action_button'

app/views/frontend/projects/show.html.slim
- content_for(:title) { @project.name }
- content_for(:description) { @project.description }
- content_for(:image_url) { @project.tile_cover.url(:main, only_path: false) }

.project-details.container-fluid
  .title-top
    h1 = @project.name
    .descr = @project.description

  .container
    - if @project.video.present?
        = video_tag @project.video.url, autoplay: true
    - elsif @project.gallery.gallery_photos.count > 0
      = render 'gallery', gallery: @project.gallery
    - elsif @project.cover.present?
      = image_tag @project.cover.url(:main), class: 'top-image'

  .container
    .row.project-content-container
      .col-md-9.content-column.wysiwyg-content
        == @project.content
      .col-md-3.services-column
        - if @project.services.any?
          .services
            h2 Services
            ul
              - @project.services.each do |service|
                li = service

        - if @project.link.present?
          = link_to 'VISIT SITE', @project.link, class: 'link', target: '_blank'


  .share
    = widget :social_share, :show, url: frontend_project_url(@project), title: @project.name, image: (@project.cover.url(:main) if @project.cover.present?)

  .more-work More Work

  = widget :projects_recent, :show, excluded: @project
  /= render 'action_button'