config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, module: :devise, path: 'backend/auth'

  root to: 'frontend/site#index'
  namespace :frontend, path: '' do
    get 'about' => 'site#about'
    get 'contact' => 'site#contact'

    resources :projects,  only: [:index, :show]
    resources :applications, only: [:create]
    resources :vacancies, only: [:index]

    resources :news_articles, path: 'news', only: [:index, :show]
  end

  get 'admin' => redirect('backend')
  namespace :backend do
    get '/' => redirect('backend/news')

    resources :projects
    #resources :vacancies
    resources :applications, only: [:index, :show, :destroy]
    resources :news_articles, path: 'news', except: [:show]

    resources :galleries, only: [] do
      resources :gallery_photos, only: [:index, :create, :destroy], path: 'photos'
    end

    resources :admin_users, path: 'admin-users'

    resources :wysiwyg_attachments, only: [:index, :create, :show]
    resources :wysiwyg_videos, only: [:index, :create, :show]

    resources :site_settings, path: 'settings', only: [:index] do
      collection do
        put :update
      end
    end
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  devise :database_authenticatable, :rememberable, :trackable, :validatable
end

app/controllers/backend/admin_users_controller.rb
module Backend
  class AdminUsersController < BackendController
    before_action :set_user, only: [:show, :edit, :update, :destroy]

    def index
      @users = AdminUser.paginate(paginate_params)
    end

    def show
    end

    def new
      @user = AdminUser.new
    end

    def edit
    end

    def create
      @user = AdminUser.new(user_params)

      if @user.save
        redirect_to backend_admin_users_path, notice: 'Пользователь был успешно добавлен в систему'
      else
        flash[:error] = 'Произошла ошибка при добавлении пользователя'
        render :new
      end
    end

    def update
      if @user.update(user_params)
        redirect_to backend_admin_users_path, notice: 'Пользователь был успешно обновлен'
      else
        flash[:error] = 'Произошла ошибка при обновлении пользователя'
        render :edit
      end
    end

    def destroy
      if AdminUser.count <= 1
        flash[:error] = 'Вы не можете удалить последнего администратора'
        redirect_to backend_admin_users_url
      else
        @user.destroy
        redirect_to backend_admin_users_url, notice: 'Пользователь был успешно удален'
      end
    end

    private
    def set_user
      @user = AdminUser.find(params[:id])
    end

    def user_params
      params.require(:admin_user).permit(:email, :password)
    end
  end
end

app/controllers/backend/applications_controller.rb
class Backend::ApplicationsController < BackendController
  before_action :find_application, only: [:show, :destroy]

  def index
    @applications = Application.order('created_at DESC')
  end

  def show
  end

  def destroy
    @application.destroy
    redirect_to backend_applications_path, notice: 'Application was successfully destroyed.'
  end

  protected
  def find_application
    @application = Application.find(params[:id])
  end
end

app/controllers/backend/galleries_controller.rb
class GalleriesController < BackendController

  def edit

  end

  def update

  end

  def find_gallery
    @gallery = Gallery.find(params[:id])
  end

end

app/controllers/backend/gallery_photos_controller.rb
class Backend::GalleryPhotosController < BackendController
  before_action :find_gallery
  respond_to :json
  def index
    @photos = @gallery.gallery_photos.order('created_at asc')
  end

  def create
    @photo = GalleryPhoto.new(photo: params[:file], gallery: @gallery)
    if @photo.save
      render 'show'
    else
      render nothing: true
    end
  end

  def destroy
    @photo = @gallery.gallery_photos.find(params[:id])
    @photo.destroy

    render nothing: true
  end

  def find_gallery
    @gallery = Gallery.find(params[:gallery_id])
  end
end

app/controllers/backend/news_articles_controller.rb
class Backend::NewsArticlesController < BackendController
  before_action :find_news_article, only: [:show, :edit, :update, :destroy]

  def index
    @q = NewsArticle.latest.search(params[:q])
    @news_articles = @q.result(distinct: true).paginate(paginate_params)
  end

  def new
    @news_article = NewsArticle.new
  end

  def create
    @news_article = NewsArticle.new(news_article_params)
    if @news_article.save
      redirect_to backend_news_articles_path, notice: 'Article was successfully updated'
    else
      render 'new', alert: 'Check out the errors below'
    end
  end

  def edit
  end

  def update
    if @news_article.update(news_article_params)
      redirect_to backend_news_articles_path, notice: 'Article was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @news_article.destroy
    redirect_to backend_news_articles_path, notice: 'Article was successfully destroyed'
  end

  protected
  def find_news_article
    @news_article = NewsArticle.friendly.find(params[:id])
  end

  def news_article_params
    params.require(:news_article).permit(:title, :readout, :content, :cover, :author, :published)
  end
end

app/controllers/backend/projects_controller.rb
class Backend::ProjectsController < BackendController
  before_action :find_item, only: [:show, :edit, :update, :destroy]


  def index
    @q = Project.latest.search(params[:q])
    @projects = @q.result(distinct: true).paginate(paginate_params)
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to backend_projects_path, notice: 'Project was successfully updated'
    else
      render 'new', alert: 'Check out the errors below'
    end
  end

  def edit
  end

  def update
    if @project.update(project_params)
      redirect_to edit_backend_project_path(@project), notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to backend_projects_path, notice: 'Project was successfully destroyed'
  end

  protected
  def find_item
    @project = Project.friendly.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :description, :content, :tile_cover, :carousel_cover, :in_carousel,
                                    :cover, :video, :virtual_services, :carousel_title, :carousel_description, :link,
                                    :carousel_text_color)
  end
end

app/controllers/backend/site_settings_controller.rb
class Backend::SiteSettingsController < BackendController

  def index
    @site_settings = SiteSetting.order('id asc')
  end

  def update
    keys = site_settings_params.map {|k, _| k}
    vals = site_settings_params.map {|_, v| v}
    @site_settings = SiteSetting.update(keys, vals)
    if @site_settings.all? { |setting| setting.valid? }
      redirect_to backend_site_settings_path, notice: 'Settings were successfully updated'
    else
      flash.now[:alert] = 'Check out the error below'
      render 'index'
    end
  end

  private
  def site_settings_params
    params.require(:site_settings).permit!
  end
end

app/controllers/backend/vacancies_controller.rb
class Backend::VacanciesController < BackendController
  before_action :find_vacancy, only: [:show, :edit, :update, :destroy]
  def index
    @q = Vacancy.ransack(params[:q])
    @vacancies = @q.result(distinct: true).paginate(paginate_params)
  end

  def new
    @vacancy = Vacancy.new
  end

  def create
    @vacancy = Vacancy.new(vacancy_params)
    if @vacancy.save
      redirect_to backend_vacancies_path, notice: 'Vacancy was created'
    else
      render 'new', alert: 'Were errors'
    end
  end

  def show

  end

  def edit

  end

  def update
    if @vacancy.update(vacancy_params)
      redirect_to backend_vacancies_path, notice: 'Vacancy was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @vacancy.destroy
    redirect_to backend_vacancies_path, notice: 'Vacancy was successfully destroyed.'
  end

  protected
  def find_vacancy
    @vacancy = Vacancy.friendly.find(params[:id])
  end

  def vacancy_params
    params.require(:vacancy).permit(:position, :location, :content)
  end
end

app/controllers/backend/wysiwyg_attachments_controller.rb
class Backend::WysiwygAttachmentsController < BackendController
  def index
    @attachments = WysiwygAttachment.order('created_at desc').limit(12)

    render 'index'
  end

  def create
    @attachment = WysiwygAttachment.create(image: params.permit(:attachment)['attachment'])
    render 'show'
  end

  def show
    @attachment = WysiwygAttachment.find(params[:id])

    render 'show'
  end
end

app/controllers/backend/wysiwyg_videos_controller.rb
class Backend::WysiwygVideosController < BackendController
  def index
    @videos = WysiwygVideo.order('created_at desc').limit(12)

    render 'index'
  end

  def create
    @video = WysiwygVideo.create(video: params.permit(:video)['video'])
    render 'show'
  end

  def show
    @attachment = WysiwygVideo.find(params[:id])

    render 'show'
  end
end

app/controllers/backend_controller.rb
module Backend; end;

class BackendController < ActionController::Base
  helper BackendHelper

  WillPaginate.per_page = 20

  layout 'backend'

  before_action :authenticate_admin_user!

  def paginate_params
    { page: params[:page], per_page: 20 }
  end
end

app/helpers/backend_helper.rb
module BackendHelper
  def paginate_list(collection)
    will_paginate collection, renderer: BootstrapPagination::Rails
  end

  def show_table_item_button(path)
    link_to path, class: 'btn btn-sm btn-default' do
      raw('<i class="ai ai-remove-red-eye"></i>')
    end
  end

  def edit_table_item_button(path)
    link_to path, class: 'btn btn-sm btn-default' do
      raw('<i class="ai ai-mode-edit"></i>')
    end
  end

  def remove_table_item_button(path)
    link_to path, class: 'btn btn-sm btn-default', method: :delete, data: { confirm: 'Do you really want to delete this item?' } do
      raw('<i class="ai ai-delete"></i>')
    end
  end

  def edit_item_button(path)
    link_to path, class: 'btn btn-info' do
      raw('<i class="ai ai-mode-edit"></i>')
    end
  end

  def remove_item_button(path)
    link_to path, class: 'btn btn-danger', method: :delete, data: { confirm: 'Do you really want to delete this item?' } do
      raw('<i class="ai ai-delete"></i>')
    end
  end

  def back_to_list_button(path)
    link_to path, class: 'btn btn-default' do
      raw('<i class="ai ai-keyboard-backspace"></i>')
    end
  end

  def form_buttons(form, cancel_path: nil, submit_label: 'Save')
    content_tag('div', class: 'form-group no-margin btn-group') do
        cancel_button = link_to('Cancel', cancel_path, class: 'btn btn-default btn-lg') if cancel_path
        submit_button = form.button(:submit, submit_label, class: 'btn btn-lg btn-success')

        raw(cancel_button.to_s + submit_button)
    end
  end
end

app/views/backend/admin_users/_form.html.slim
= simple_form_for [:backend, @user], html: { class: 'form panel form-vertical' }, wrapper: :vertical_form do |f|
  .panel-body
    = f.input :email, placeholder: 'email@domain.com'
    = f.input :password
  .panel-footer
    = form_buttons f, cancel_path: backend_admin_users_path

app/views/backend/admin_users/edit.html.slim
- content_for(:title) { "User #{@user.email}" }
.page-header
  h3 User #{@user.email}
.pa-md
  = render 'form'

app/views/backend/admin_users/index.html.slim
- content_for(:title) { 'Users' }
.page-header
  .btn-toolbar.pull-right
    .btn-group
      = link_to new_backend_admin_user_path, class: 'btn btn-lg btn-success' do
        i.ai.ai-person-add
  h3 Users

.table-responsive
  table.table.table-striped.table-hover
    thead
      tr
        th width="3%"
          .checkbox.custom-info.mt-0.mb-0
            label
              input type="checkbox"
        th Email
        th.actions
    tbody
      - @users.each do |user|
        tr
          td
            .checkbox.custom-info.mt-0.mb-0
              label
                input type="checkbox" /
          td= link_to user.email, backend_admin_user_path(user)

          td.text-right
            .btn-group.toolbar
              = show_table_item_button backend_admin_user_path(user)
              = edit_table_item_button edit_backend_admin_user_path(user)
              = remove_table_item_button backend_admin_user_path(user)

  = paginate_list @users

app/views/backend/admin_users/new.html.slim
- content_for(:title) { 'New user' }
.page-header
  h3 New user

.pa-md
  = render 'form'

app/views/backend/admin_users/show.html.slim
- content_for(:title) { "#{AdminUser.model_name.human} ##{@user.email}" }
.page-header
  .btn-toolbar.pull-right
    .btn-group
      = back_to_list_button backend_admin_users_path
      = edit_item_button edit_backend_admin_user_path(@user)
      = remove_item_button backend_admin_user_path(@user)
  h3
    => "User #{@user.email}"
= render 'backend/shared/flash_messages', flash: flash
.pa-md
  .row
    .col-md-12
      .panel
        .panel-body
          .field
            | #{AdminUser.human_attribute_name('id')}: #{@user.id}
          .field
            | #{AdminUser.human_attribute_name('email')}: #{@user.email}
          .field
            | #{AdminUser.human_attribute_name('sign_in_count')}: #{@user.sign_in_count}
          .field
            | #{AdminUser.human_attribute_name('current_sign_in_at')}: #{I18n.l @user.current_sign_in_at, format: :short}
          .field
            | #{AdminUser.human_attribute_name('current_sign_in_ip')}: #{@user.current_sign_in_ip}
          .field
            | #{AdminUser.human_attribute_name('created_at')}: #{I18n.l @user.created_at, format: :short}
          .field
            | #{AdminUser.human_attribute_name('updated_at')}: #{I18n.l @user.updated_at, format: :short}